### PR TITLE
Translate into Chinese

### PR DESCRIPTION
**Pull request by Hawstein**
I love this Scala style guide and like to share it with Scala users in China.

### CODE REVIEW

**Comment by rxin** [comment]
@Hawstein thanks a lot for the contribution.

If we were going to merge this, I have a few requests:

1. It should say at the top that this is contributed by the community and does not always stay up-to-date as the English version. And you should acknowledge you for spending the time to translate this.

2. Are you willing to be the maintainer for this? From time to time when we update the guide, I will ping you to update the Chinese version.

**Comment by rxin** [comment]
BTW you should add the email you used on your commit to your github profile.

**Comment by Hawstein** [comment]
@rxin hi, for your requests:

1. I just updated the Chinese version to add a declaration section at the top. 

2. Yes, I would like to maintain the doc. If the original guide is updated, I will update the Chinese version ASAP if I have time.

In addition, I have changed my commit email. The previous one is totally an accident. Sorry for that.

**Comment by rxin** [comment]
Thanks - I'm merging this in.

**Comment by jacksu** [comment]
very good

**Pull request merged**
