### PR TITLE
Prefer existing well-tested methods over reinventing the wheel

### PR DESCRIPTION
**Pull request by zsxwing**
Add a new section: Prefer existing well-tested methods over reinventing the wheel

### CODE REVIEW

**Comment by zsxwing** [comment]
cc @rxin

**Comment by rxin** [comment]
LGTM - thanks!

**Comment by rxin** [comment]
cc @HyukjinKwon want to add the korean version?

**Comment by HyukjinKwon** [comment]
Definitely. Thank you for cc'ing me.

**Pull request merged**
