### PR TITLE
Clarification for enumerations

### PR DESCRIPTION
**Pull request by MaxGekk**
In the PR, I propose to clearly describe the convention for enumeration classes/objects and its values. Also I added an example.

### CODE REVIEW

**Comment by MaxGekk** [comment]
@rxin Please, take a look at the PR.

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me, @MaxGekk . But, this is `Databricks` repo. :)

**Comment by srowen** [comment]
Yeah, it's public though unless I'm totally missing something and serves as the de facto Spark style guide? anyway you're welcome to comment in any event of course. And make changes, etc

**Comment by rxin** [comment]
Thanks @MaxGekk

**Pull request merged**
