### PR TITLE
Add variable naming section for Korean and fix miscellaneous inconsistent things for guidelines

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR adds variable naming section for Korean guideline and fixes several miscellaneous inconsistent things across guidelines.

"miscellaneous inconsistent things" include below:

**English**
1. Adds the history, `2016-06-21: Added [Variable Naming Convention](#variable-naming) section`
2. Fixes a typo in the Java example in Java Interoperability, (from `method1` to `method2`).
3. Fixes the Java example in Java Interoperability, (add `void` in the function definition).

**Korean**
1. `, i.e. Try vs try` to ` (Try vs try)`
2.  ` a + 1` to `a += 1`, and `count + 1` to `count += 1`
3. Remove duplicated words `이는,`. (`이는, 이는,`  to `이는,`)
4. Fixes a typo in the Java example in Java Interoperability, (from `method1` to `method2`).
5. Fixes the Java example in Java Interoperability, (add `void` in the function definition).

**Chinese**
1.  `, i.e. Try vs try` to ` (Try vs try)` in the contents.
2. Fixes the Java example in Java Interoperability, (add `void` in the function definition).

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Mainly the contents in https://github.com/databricks/scala-style-guide/pull/32 were translated here.

**Comment by yunpark93** [comment]
Could we change "변수 이름 명명 규칙" to "변수 명명 규칙"?

@rxin - other than this one comment, LGTM

**Comment by HyukjinKwon** [comment]
Sure, thanks!

**Comment by HyukjinKwon** [comment]
(Some more minor fixes were added)

**Comment by rxin** [comment]
Thanks - merging this in.

**Pull request merged**
